GET http://localhost:3000/todos/?category=ATHOME
###
GET http://localhost:3000/todos/1/


###
GET http://localhost:3000/agenda/?date=2020-09-22



###
POST http://localhost:3000/todos/
Content-Type:application/json

{
    "id":6,
    "todo": "Finalize event theme",
    "priority": "LOW",
    "status": "TO DO",
    "category": "HOME",
    "dueDate": "2021-02-22"
}

###
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
    "category": "ATHOME" 
}